---
extends: default

ignore: []

rules:
  comments-indentation: enable
  document-start: enable
  indentation:
    spaces: 2
    indent-sequences: consistent
  line-length: disable
  truthy:
    allowed-values: ["true", "false"]
