# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

env:
  SOPS_AGE_KEY_FILE: "{{.HOME}}/.config/age/misklinga.txt"

vars: {}

includes:
  precommit: .taskfiles/PrecommitTasks.yaml
  sops: .taskfiles/SopsTasks.yaml

tasks:
  default:
    desc: List all tasks.
    cmd: task --list-all
