# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

env: {}

vars:
  ANSIBLE_ROOT_DIR: "{{.ROOT_DIR}}/ansible"

includes:
  precommit: .taskfiles/PrecommitTasks.yaml
  docs: .taskfiles/DocsTasks.yaml

  sops: .taskfiles/SopsTasks.yaml
  ansible: .taskfiles/AnsibleTasks.yaml

tasks:
  default:
    desc: List all tasks.
    cmd: task --list-all
